#!/bin/bash
if [ $# -le 1 ]; then
	/usr/bin/echo "Wrong Parameters"
	exit -1
fi

gadgetPath="/sys/kernel/config/usb_gadget/g1"
msdPath="${gadgetPath}/functions/mass_storage.usb0/lun.0"
filePath="${msdPath}/file"
cdromPath="${msdPath}/cdrom"
UDCPath="${gadgetPath}/UDC"

imagePath="$2"

valInCdRom=`/usr/bin/cat ${cdromPath}`
targetValueInCdRom=0
echo "" > $filePath
if [ $1 == "cdrom" ]; then
	targetValueInCdRom=1
fi

if [ $targetValueInCdRom -ne $valInCdRom ]; then
	/usr/bin/echo "" > $UDCPath
	/usr/bin/echo $targetValueInCdRom > $cdromPath
	/usr/bin/ls /sys/class/udc > $UDCPath
	/usr/bin/chmod 777 /dev/hidg0
	/usr/bin/chmod 777 /dev/hidg1
fi

/usr/bin/echo $imagePath > $filePath
